# detr_resnet_50_panoptic.yaml

# Annotator-specific settings
annotator:
  name: detr_resnet_50_panoptic
  type: DETR_Panoptic  # Type of model/algorithm used for this annotator
  task_type: SegmentationTask  # Type of task performed by this annotator
  detected_property: mask  # The property that is being detected (in this case, segmentation masks)

# Model-specific imports and configurations
imports:
  model_class: transformers.DetrForSegmentation  # Class to import for the model
  processor_class: transformers.DetrFeatureExtractor  # Class to import for the processor

model:
  model_name: facebook/detr-resnet-50-panoptic  # Pretrained model name or path for segmentation

processor:
  processor_name: facebook/detr-resnet-50-panoptic  # Processor name or path (same as model)

# ROS topics specific to this annotator
ros:
  result_topic: annotators/detr_resnet_50_panoptic/result  # Topic for publishing detection results
  image_topic: annotators/detr_resnet_50_panoptic/image  # Topic for publishing annotated images

# Segmentation-related settings
detection:
  labels: 
    - person
    - bicycle
    - car
    - motorcycle
    - airplane
    - bus
    - train
    - truck
    - boat
    - traffic light
    - fire hydrant
    - stop sign
    - parking meter
    - bench
    - bird
    - cat
    - dog
    - horse
    - sheep
    - cow
    - elephant
    - bear
    - zebra
    - giraffe
    - backpack
    - umbrella
    - handbag
    - tie
    - suitcase
    - frisbee
    - skis
    - snowboard
    - sports ball
    - kite
    - baseball bat
    - baseball glove
    - skateboard
    - surfboard
    - tennis racket
    - bottle
    - wine glass
    - cup
    - fork
    - knife
    - spoon
    - bowl
    - banana
    - apple
    - sandwich
    - orange
    - broccoli
    - carrot
    - hot dog
    - pizza
    - donut
    - cake
    - chair
    - couch
    - potted plant
    - bed
    - dining table
    - toilet
    - TV
    - laptop
    - mouse
    - remote
    - keyboard
    - cell phone
    - microwave
    - oven
    - toaster
    - sink
    - refrigerator
    - book
    - clock
    - vase
    - scissors
    - teddy bear
    - hair drier
    - toothbrush
  confidence_threshold: 0.9  # Confidence threshold for segmentation
  iou_threshold: 0.45  # Intersection over Union threshold for segmentation masks
