# segformer_b1.yaml

# Annotator-specific settings
annotator:
  name: segformer_b1
  type: Segformer  # Type of model/algorithm used for this annotator
  task_type: ImageSegmentation  # Type of task performed by this annotator
  detected_property: ObjectType  # The property that is being detected (in this case, segmentation masks)

# Model-specific imports and configurations
imports:
  model_class: transformers.SegformerForSemanticSegmentation  # Class to import for the model
  processor_class: transformers.SegformerFeatureExtractor  # Class to import for the processor

model:
  model_name: nvidia/segformer-b1-finetuned-ade-512-512  # Pretrained model name or path for segmentation

processor:
  processor_name: nvidia/segformer-b1-finetuned-ade-512-512  # Processor name or path (same as model)

# ROS topics specific to this annotator
ros:
  result_topic: annotators/segformer_b1/result  # Topic for publishing detection results
  image_topic: annotators/segformer_b1/image  # Topic for publishing annotated images

# Segmentation-related settings
detection:
  labels: 
    - wall
    - building
    - sky
    - floor
    - tree
    - ceiling
    - road
    - bed 
    - windowpane
    - grass
    - cabinet
    - sidewalk
    - person
    - earth
    - door
    - table
    - mountain
    - plant
    - curtain
    - chair
    - car
    - water
    - painting
    - sofa
    - shelf
    - house
    - sea
    - mirror
    - rug
    - field
    - armchair
    - seat
    - fence
    - desk
    - rock
    - wardrobe
    - lamp
    - bathtub
    - railing
    - cushion
    - base
    - box
    - column
    - signboard
    - chest of drawers
    - counter
    - sand
    - sink
    - skyscraper
    - fireplace
    - refrigerator
    - grandstand
    - path
    - stairs
    - runway
    - case
    - pool table
    - pillow
    - screen door
    - stairway
    - river
    - bridge
    - bookcase
    - blind
    - coffee table
    - toilet
    - flower
    - book
    - hill
    - bench
    - countertop
    - stove
    - palm
    - kitchen island
    - computer
    - swivel chair
    - boat
    - bar
    - arcade machine
    - hovel
    - bus
    - towel
    - light
    - truck
    - tower
    - chandelier
    - awning
    - streetlight
    - booth
    - television receiver
    - airplane
    - dirt track
    - apparel
    - pole
    - land
    - bannister
    - escalator
    - ottoman
    - bottle
    - buffet
    - poster
    - stage
    - van
    - ship
    - fountain
    - conveyer belt
    - canopy
    - washer
    - plaything
    - swimming pool
    - stool
    - barrel
    - basket
    - waterfall
    - tent
    - bag
    - minibike
    - cradle
    - oven
    - ball
    - food
    - step
    - tank
    - trade name
    - microwave
    - pot
    - animal
    - bicycle
    - lake
    - dishwasher
    - screen
    - blanket
    - sculpture
    - hood
    - sconce
    - vase
    - traffic light
    - tray
    - ashcan
    - fan
    - pier
    - crt screen
    - plate
    - monitor
    - bulletin board
    - shower
    - radiator
    - glass
    - clock
    - flag
  confidence_threshold: 0.9  # Confidence threshold for segmentation
  iou_threshold: 0.45  # Intersection over Union threshold for segmentation masks
